name: unit-test
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - '**'
        types: [ opened, synchronize, reopened ]

jobs:
    unittest:
        name: run unittest
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: Show CPU Model and Free Space
                run: |
                    echo -e "$HOSTNAME"
                    echo -e "Total CPU cores\t: $(nproc)"
                    cat /proc/cpuinfo | grep 'model name'
                    free -h
            -   name: Set up JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: 21

            -   name: gradle build
                uses: burrunan/gradle-cache-action@v2
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    gradle-version: wrapper
                    remote-build-cache-proxy-enabled: false
                    multi-cache-enabled: false
                    read-only: ${{ github.ref != 'refs/heads/main' }}
                    arguments: clean build --build-cache --warn

            -   name: Publish Unit Test Results
                uses: EnricoMi/publish-unit-test-result-action@v2
                if: always()
                with:
                    junit_files: "**/build/test-results/test/*.xml"

            -   name: Jacoco Report to PR
                id: jacoco
                uses: madrapps/jacoco-report@v1.7.1
                with:
                    paths: |
                        ${{ github.workspace }}/build/jacoco/jacocoTestReport.xml,
                    token: ${{ secrets.GITHUB_TOKEN }}
                    min-coverage-overall: 40
                    min-coverage-changed-files: 60
                    title: Code Coverage Report
                    debug-mode: false
                    update-comment: true

            -   name: Get the Coverage info
                run: |
                    echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
                    echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"